spring:
  application:
    name: company-directory
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 'strong-password'
  jpa:
    show-sql: true
    #open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true

external:
  employee-service:
    url: http://localhost:3001

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    tags:
      application: myapp
    enable:
      hibernate: true
      jvm: true
      process: true
      system: true
  prometheus:
    metrics:
      export:
        enabled: true