-- Schema for Company Directory (H2 using explicit sequences for portability)


CREATE TABLE companies (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    vat VARCHAR(32)
);

-- departments defined before employees; chief_id added now, FK added after employees table is created
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    company_id BIGINT NOT NULL,
    chief_user_id VARCHAR(20) ,
    CONSTRAINT fk_department_company FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    user_id VARCHAR(20)  NOT NULL ,
    department_id BIGINT NOT NULL,
    CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES departments(id)
);

-- Now that employees exists, add FK and unique constraint for chief
ALTER TABLE employees ADD CONSTRAINT ux_employees_user_id UNIQUE (user_id);

CREATE UNIQUE INDEX ux_departments_chief ON departments(chief_user_id);
ALTER TABLE departments
    ADD CONSTRAINT fk_department_chief FOREIGN KEY (chief_user_id) REFERENCES employees(user_id);
--
-- CREATE INDEX idx_departments_company ON departments(company_id);
-- CREATE INDEX idx_employees_department ON employees(department_id);
-- CREATE INDEX idx_companies_name ON companies(name);
-- CREATE UNIQUE INDEX idx_companies_vat ON companies(vat);
-- CREATE INDEX idx_departments_name ON departments(name);
-- CREATE INDEX idx_employees_last_first ON employees(last_name, first_name);
