CREATE TABLE trainings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(1000),
    category     VARCHAR(100),
    duration_days INTEGER
);

CREATE TABLE employee_trainings (
    employee_id BIGINT NOT NULL,
    training_id BIGINT NOT NULL,
    PRIMARY KEY (employee_id, training_id),
    CONSTRAINT fk_employee_trainings_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_employee_trainings_training FOREIGN KEY (training_id) REFERENCES trainings(id)
);

CREATE INDEX idx_employee_trainings_employee ON employee_trainings(employee_id);
CREATE INDEX idx_employee_trainings_training ON employee_trainings(training_id);
